# Generated by Django 4.2.17 on 2024-12-06 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.SmallIntegerField()),
                ('state', models.SmallIntegerField()),
                ('amount', models.FloatField()),
                ('entry_price', models.FloatField()),
                ('leverage', models.SmallIntegerField()),
                ('take_profit', models.FloatField()),
                ('stop_loss', models.FloatField()),
            ],
        ),
    ]
